/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReassignView.java
 *
 * Created on Nov 26, 2009, 7:48:08 PM
 */

package backend.assignmentdist;

import backend.DatabaseIO;
import javax.swing.JList;
import org.tmatesoft.sqljet.core.table.ISqlJetCursor;
import utils.ErrorView;

/**
 *
 * @author jonathan
 */
public class FinalProjectAssigner extends javax.swing.JFrame {

    /** Creates new form ReassignView */
    public FinalProjectAssigner() {
        initComponents();
        this.populateLists();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        assignmentList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        reassignButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        toTAList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        toStudentList = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        assignmentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        assignmentList.setName("assignmentList"); // NOI18N
        assignmentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(assignmentList);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gradesystem.GradeSystemApp.class).getContext().getResourceMap(FinalProjectAssigner.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        reassignButton.setText(resourceMap.getString("reassignButton.text")); // NOI18N
        reassignButton.setName("reassignButton"); // NOI18N
        reassignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reassignButtonActionPerformed(evt);
            }
        });

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        toTAList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        toTAList.setName("toTAList"); // NOI18N
        toTAList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toTAListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(toTAList);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        toStudentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        toStudentList.setName("toStudentList"); // NOI18N
        jScrollPane5.setViewportView(toStudentList);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reassignButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(reassignButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentListMouseClicked
        this.updateFormComponents();
    }//GEN-LAST:event_assignmentListMouseClicked

    private void reassignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reassignButtonActionPerformed
        String newTA = (String) toTAList.getSelectedValue();

        //modify database
//        try {
//            ISqlJetCursor cursor = DatabaseIO.getItemWithFilter("assignment_dist", "ta_login_dist", oldTA);
//            if (cursor.eof()) {
//                cursor.close();
//                return;
//            }
//            try {
//                String assignedStudents = cursor.getString((String) assignmentList.getSelectedValue());
//                System.out.println("before: " + assignedStudents);
//                if (assignedStudents == null) {
//                    assignedStudents = "";
//                    System.out.println("null");
//                }
//                String[] students = assignedStudents.split(", ");
//                Vector studList = new Vector(Arrays.asList(students));
//                studList.remove(student);
//                String row[] = (String[]) DatabaseIO.getDataRow("assignment_dist", DatabaseIO.getRowID("assignment_dist", "ta_login_dist", oldTA));
//                System.out.println("row is " + row);
//                //Arrays.sort(row, new StringComparator());
//                //System.out.println("sorted successfully");
//                int i = 0;
//                while (i < row.length) {
//                    System.out.println(row[i]);
//                    i++;
//                }
//                //Arrays.toString(studList.toArray());
//                //DatabaseIO.update(DatabaseIO.getRowID("assignment_dist", "ta_login_dist", oldTA), "assignment_dist", Arrays.toString(studList.toArray()));
//            } finally {
//                cursor.close();
//            }
//        } catch (Exception e) {
//            //new ErrorView(e);
//            e.printStackTrace();
//        }
        
        //update XML files
        //RubricManager.reassignXML(Project.getInstance((String)assignmentList.getSelectedValue()), oldTA, student, newTA);

        //still need to remove old XMLs
    }//GEN-LAST:event_reassignButtonActionPerformed

    private void toTAListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toTAListMouseClicked
        this.updateFormComponents();
    }//GEN-LAST:event_toTAListMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProjectAssigner().setVisible(true);
            }
        });
    }

    private void populateLists() {
        assignmentList.setListData(DatabaseIO.getProjectNames());
        if (assignmentList.getModel().getSize() > 0) {
            assignmentList.setSelectedIndex(0);
        }

        toTAList.setListData(DatabaseIO.getTANames());
        if (toTAList.getModel().getSize() > 0) {
            toTAList.setSelectedIndex(0);
        }

        this.populateStudentList(toStudentList, (String) toTAList.getSelectedValue());
    }

    private void populateStudentList(JList list, String user) {
        try {
            ISqlJetCursor cursor = DatabaseIO.getItemWithFilter("assignment_dist", "ta_login_dist", user);
            if (cursor.eof()) {
                cursor.close();
                return;
            }
            try {
                String s = cursor.getString((String) assignmentList.getSelectedValue());
                if (s == null) {
                    s = "";
                }
                String[] ss = s.split(", ");
                list.setListData(ss);
                if (list.getModel().getSize() > 0) {
                    list.setSelectedIndex(0);
                }

            } finally {
                cursor.close();
            }
        } catch (Exception e) {
            new ErrorView(e);
        }

    }

    private void updateFormComponents() {
//        assignmentList.setListData(DatabaseIO.getProjectNames());
//        if (assignmentList.getModel().getSize() > 0) {
//            assignmentList.setSelectedIndex(0);
//        }
        this.populateStudentList(toStudentList, (String) toTAList.getSelectedValue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList assignmentList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton reassignButton;
    private javax.swing.JList toStudentList;
    private javax.swing.JList toTAList;
    // End of variables declaration//GEN-END:variables

}
