package gradesystem.services;


import gradesystem.Allocator;
import gradesystem.Allocator.SingletonAllocation;
import gradesystem.config.Assignment;
import gradesystem.database.Group;
import gradesystem.handin.DistributablePart;
import gradesystem.handin.Handin;
import java.io.File;
import org.junit.Before;
import org.junit.Test;
import utils.CalendarUtilities;
import utils.UserUtilities;

import static org.junit.Assert.*;
import static org.easymock.EasyMock.*;

/**
 * Tests the paths generated by {@link PathServicesImpl}.
 *
 * @author jak2
 */
public class PathServicesTest
{
    private static final String COURSE = "cs001";
    private static final int YEAR = 1988;

    private static final String ASSIGNMENT_NAME = "the asgn";
    private static final String PART_NAME = "the dist part";
    private static final String TA_LOGIN = "jak2";
    private static final String GROUP_NAME = "the group";

    private Group _group;
    private Assignment _assignment;
    private Handin _handin;
    private DistributablePart _part;
    private PathServices _service;

    @Before
    public void setup()
    {
        //Mock group
        _group = new Group(GROUP_NAME, "aunger", "jeldridg");

        //Create mocked assignment, handin, and part objects
        _assignment = createMock(Assignment.class);
        expect(_assignment.getName()).andReturn(ASSIGNMENT_NAME).anyTimes();

        _handin = createMock(Handin.class);
        expect(_handin.getAssignment()).andReturn(_assignment).anyTimes();
        expect(_assignment.getHandin()).andReturn(_handin).anyTimes();

        _part = createMock(DistributablePart.class);
        expect(_part.getName()).andReturn(PART_NAME).anyTimes();
        expect(_part.getAssignment()).andReturn(_assignment).anyTimes();
        expect(_part.getHandin()).andReturn(_handin).anyTimes();

        replay(_assignment);
        replay(_handin);
        replay(_part);

        //Mock out course information
        final CourseInfo courseInfo = createMock(CourseInfo.class);
        expect(courseInfo.getCourse()).andReturn(COURSE).anyTimes();
        replay(courseInfo);
        SingletonAllocation<CourseInfo> courseInfoAlloc =
            new SingletonAllocation<CourseInfo>()
            {
                public CourseInfo allocate() { return courseInfo; };
            };

        //Mock out calendar info
        final CalendarUtilities calendarUtil = createMock(CalendarUtilities.class);
        expect(calendarUtil.getCurrentYear()).andReturn(YEAR).anyTimes();
        replay(calendarUtil);
        SingletonAllocation<CalendarUtilities> calendarUtilAlloc =
            new SingletonAllocation<CalendarUtilities>()
            {
                public CalendarUtilities allocate() { return calendarUtil; };
            };

        //Mock out user utilities
        final UserUtilities userUtil = createMock(UserUtilities.class);
        expect(userUtil.getUserLogin()).andReturn(TA_LOGIN).anyTimes();
        replay(userUtil);
        SingletonAllocation<UserUtilities> userUtilAlloc =
            new SingletonAllocation<UserUtilities>()
            {
                public UserUtilities allocate() { return userUtil; };
            };

        new Allocator.Customizer()
                .setCourseInfo(courseInfoAlloc)
                .setCalendarUtils(calendarUtilAlloc)
                .setUserUtils(userUtilAlloc)
                .customize();

        _service = Allocator.getPathServices();
    }


    @Test
    public void testGetCourseDir()
    {
        File expected = new File("/course/" + COURSE);

        assertEquals(expected, _service.getCourseDir());
    }

    @Test
    public void testGetHandinDir()
    {
        File expected = new File("/course/" + COURSE + "/handin/" +
                ASSIGNMENT_NAME + "/" + YEAR);
        
        assertEquals(expected, _service.getHandinDir(_handin));
    }

    @Test
    public void testGetCakehatDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat");

        assertEquals(expected, _service.getCakehatDir());
    }

    @Test
    public void testGetConfigurationFile()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/" + YEAR +
                "/config/config.xml");

        assertEquals(expected, _service.getConfigurationFile());
    }

    @Test
    public void testGetGMLDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/" + YEAR +
                "/rubrics/" + ASSIGNMENT_NAME + "/" + PART_NAME);

        assertEquals(expected, _service.getGMLDir(_part));
    }

    @Test
    public void testGroupGMLFile()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/" + YEAR +
                "/rubrics/" + ASSIGNMENT_NAME + "/" + PART_NAME + "/" +
                GROUP_NAME + ".gml");

        assertEquals(expected, _service.getGroupGMLFile(_part, _group));
    }

    @Test
    public void testGetDatabaseFile()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/" + YEAR +
                "/database/database.db");

        assertEquals(expected, _service.getDatabaseFile());
    }

    @Test
    public void testGetDatabaseBackupDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/" + YEAR +
                "/database/backups");

        assertEquals(expected, _service.getDatabaseBackupDir());
    }

    @Test
    public void testGetUserWorkspaceDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/workspaces/" +
                TA_LOGIN + "-test");

        assertEquals(expected, _service.getUserWorkspaceDir());
    }

    @Test
    public void testGetUserPartDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/workspaces/" +
                TA_LOGIN + "-test/" + ASSIGNMENT_NAME + "/" + PART_NAME);

        assertEquals(expected, _service.getUserPartDir(_part));
    }

    @Test
    public void testGetUnarchiveHandinDir()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/workspaces/" +
                TA_LOGIN + "-test/" + ASSIGNMENT_NAME + "/" + PART_NAME + "/" +
                GROUP_NAME);

        assertEquals(expected, _service.getUnarchiveHandinDir(_part, _group));
    }

    @Test
    public void testGetGroupGRDFile()
    {
        File expected = new File("/course/" + COURSE + "/.cakehat/workspaces/" +
                TA_LOGIN + "-test/" + ASSIGNMENT_NAME + "/" + GROUP_NAME + ".txt");

        assertEquals(expected, _service.getGroupGRDFile(_handin, _group));
    }
}