/*
 * AssignmentDistributorGUI.java
 *
 * Created on Sep 7, 2009, 12:53:58 PM
 */
package backend.assignmentdist;

import config.Assignment;
import config.HandinPart;
import config.TA;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Allocator;
import utils.ErrorView;

/**
 *
 * @author Paul
 * @author aunger
 */
public class AssignmentdistView extends javax.swing.JFrame {

    /** Creates new form AssignmentDistributorGUI */
    public AssignmentdistView(Assignment asgn) {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/gradesystem/resources/icons/32x32/accessories-text-editor.png")));
        } catch (Exception e) {
        }

        for (Assignment s : Allocator.getCourseInfo().getHandinAssignments()) {
            assignmentNameComboBox.insertItemAt(s, assignmentNameComboBox.getItemCount());
        }

        //create dist for assignment passed in as parameter
        if (asgn != null) {
            assignmentNameComboBox.setSelectedItem(asgn);
            this.setTitle(assignmentNameComboBox.getSelectedItem() + " - cs015 Assignment Distributor");
        }

        fillTable();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void fillTable() {

        try {
            mainTable.removeAll();
            mainTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{}));
            mainTable.removeAll();
            DefaultTableModel m = (DefaultTableModel) mainTable.getModel();
            m.addColumn("TA Login");
            m.addColumn("Difference from Average");
            for (TA grader : Allocator.getCourseInfo().getDefaultGraders()) {
                m.addRow(new String[] {grader.getLogin(), "0"});
            }

        } catch (Exception e) {
            new ErrorView(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignmentNameComboBox = new javax.swing.JComboBox();
        generateDistButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new backend.assignmentdist.AssignmentdistTable();
        setupGradingButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMcenu2 = new javax.swing.JMenu();

        assignmentNameComboBox.setFocusable(false);
        assignmentNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentNameComboBoxActionPerformed(evt);
            }
        });

        generateDistButton.setText("1. Distribute Students");
        generateDistButton.setFocusable(false);
        generateDistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDistButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("A negative value indicates no max number to grade.");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mainTable);

        setupGradingButton.setText("2. Set Up Grading");
        setupGradingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupGradingButtonActionPerformed(evt);
            }
        });

        jButton1.setText("ReAssign Grading");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        mainMenuBar.add(jMenu1);

        jMcenu2.setText("Edit");
        mainMenuBar.add(jMcenu2);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(assignmentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(generateDistButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setupGradingButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateDistButton)
                    .addComponent(setupGradingButton)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        this.setTitle(assignmentNameComboBox.getSelectedItem() + " - Assignment Distributor");
        fillTable();
    }

    private void generateDistButtonActionPerformed(java.awt.event.ActionEvent evt) {
        /** setup valiables **/

        Assignment asgn = (Assignment) assignmentNameComboBox.getSelectedItem();

        //check to make sure that there is not a dist already
        if (!Allocator.getDatabaseIO().isDistEmpty(asgn.getHandinPart())) {
            int n = JOptionPane.showConfirmDialog(new JFrame(), "A distribution already exists for " + asgn.getName() + ".\nAre you sure you want to overwrite the existing distribution?", "Confirm Overwrite", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.NO_OPTION) {
                return;
            }
        }

        //get handin logins, shuffle logins, add to deque
        ArrayList<String> handinLoginsRaw = new ArrayList<String>(asgn.getHandinPart().getHandinLogins());
        Collections.shuffle(handinLoginsRaw);
        ArrayDeque<String> handinLogins = new ArrayDeque<String>(handinLoginsRaw);

        //get all grader logins
        ArrayList<String> taLogins = new ArrayList<String>();
        for (TA ta : Allocator.getCourseInfo().getDefaultGraders()) {
            taLogins.add(ta.getLogin());
        }

        //build distribution hashmap
        Map<String, Collection<String>> distribution = new HashMap<String, Collection<String>>();
        for (String grader : taLogins) {
            distribution.put(grader, new ArrayList<String>());
        }

        /** make distribution **/

        //determine how many students to give to each TA
        Map<String, Integer> numStudsNeeded = this.calculateNumberOfHandinsPerTA(handinLogins, taLogins.size());

        //distribute all the blacklisted handins to TAs first
        boolean distBlackListSuccessful = this.assignBlackListedHandinsToTAs(distribution, numStudsNeeded, handinLogins, asgn.getHandinPart(), taLogins);
        if (!distBlackListSuccessful) {
            JOptionPane.showMessageDialog(this, "There was an error "
                        + "distributing blacklisted "
                        + "students. Please try running "
                        + "the distribution again.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //distribute the rest if the handins to TAs
        this.assignRemainingHandinsToTAs(distribution, numStudsNeeded, handinLogins, taLogins);

        //but the distribution into the DB
        Allocator.getDatabaseIO().setAsgnDist(asgn.getHandinPart(), distribution);
    }

    /**
     * calculate how many handins each TA should get based on the modifiers entered
     *
     * @param handinLogins
     * @param numberOfTAs
     * @return - map between TA and number to grade
     */
    private Map<String, Integer> calculateNumberOfHandinsPerTA(Collection<String> handinLogins, int numberOfTAs) {
        //get the current distribution modifiers from table
        DefaultTableModel modelOfTable = (DefaultTableModel) mainTable.getModel();

        //total number of handins used in calculating the average
        int calculatedTotalStudents = handinLogins.size();

        //update total number of students based modifiers from table (only used for calc of avg)
        for (int rowCount = 0; rowCount < modelOfTable.getRowCount(); rowCount++) {
            int diffFromAvg = (Integer) Integer.parseInt(modelOfTable.getValueAt(rowCount, 1).toString());
            //the extra (if TA gets less than average) students need to be go to the other TAs therefore the average and thus the total must be higher
            calculatedTotalStudents -= diffFromAvg;
        }

        //average number of students for each ta
        int avg = (int) Math.floor((double) calculatedTotalStudents / (double) numberOfTAs);

        //build hashmap of how many students each TA must grade
        HashMap<String, Integer> numStudsNeeded = new HashMap<String, Integer>();
        for (int rowCount = 0; rowCount < modelOfTable.getRowCount(); rowCount++) {
            String taLogin = (String) modelOfTable.getValueAt(rowCount, 0);
            int numToGrade = Integer.parseInt(modelOfTable.getValueAt(rowCount, 1).toString()) + avg;

            numStudsNeeded.put(taLogin, numToGrade);
        }

        return numStudsNeeded;
    }

    /**
     * assign all the blacklisted handins to TAs first so there the most possible TAs to give them to
     *
     * @param distribution
     * @param numStudsNeeded
     * @param handinLogins
     * @return - did this step work?
     */
    private boolean assignBlackListedHandinsToTAs(Map<String, Collection<String>> distribution,
                        Map<String, Integer> numStudsNeeded, Collection<String> handinLogins,
                        HandinPart handinPart, ArrayList<String> taLogins) {
        
        //get all the groups for this project (maps student login to students in their group)
        Map<String, Collection<String>> groups = Allocator.getDatabaseIO().getGroups(handinPart);

        //make a list of all blacklisted students and hashmap of all ta blacklists
        Set<String> blacklistedStudents = new HashSet<String>();
        Map<String, Collection<String>> taBlacklists = new HashMap<String, Collection<String>>();

        for (String taLogin : taLogins) {
            Collection<String> tasBlackList = Allocator.getDatabaseIO().getTABlacklist(taLogin);
            blacklistedStudents.addAll(tasBlackList);
            taBlacklists.put(taLogin, tasBlackList);
        }

        //get all handins to pick which are the blacklisted handins
        Collection<String> blacklistedHandins = handinPart.getHandinLogins();

        //remove handins which aren't blacklisted
        Iterator<String> iterator = blacklistedHandins.iterator();
        while (iterator.hasNext()) {
            if (!Allocator.getGeneralUtilities().containsAny(blacklistedStudents, groups.get(iterator.next()))) {
                iterator.remove();
            }
        }

        //add all blacklisted handins to a TA first
        for (String blStudent : blacklistedHandins) {
            Collections.shuffle(taLogins);
            boolean distributed = false;
            for (String taLogin : taLogins) {
                //if ta's blacklist does not contain students from the handin group (individuals will have a group of size 1) and ta's dist is not full
                if (!Allocator.getGeneralUtilities().containsAny(taBlacklists.get(taLogin), groups.get(blStudent))
                        && numStudsNeeded.get(taLogin) > 0) {

                    distribution.get(taLogin).add(blStudent); //add student to ta's dist
                    numStudsNeeded.put(taLogin, numStudsNeeded.get(taLogin) - 1); //reduce num ta needs
                    distributed = true;
                    break;
                }
            }
            if (!distributed) {
                return false;
            }
        }

        //remove all blacklisted students from student list since they are all distributed already
        handinLogins.removeAll(blacklistedHandins);
        return true;
    }

    /**
     * take the handins which are not on any blacklist and distributes them to TAs at random until the TA is at their limit
     *
     * @param distribution - current distribution
     * @param numStudsNeeded
     * @param handinLogins
     * @return - did this step work?
     */
    private boolean assignRemainingHandinsToTAs(Map<String, Collection<String>> distribution,
                        Map<String, Integer> numStudsNeeded, ArrayDeque<String> handinLogins,
                        ArrayList<String> taLogins) {
        
        Collections.shuffle(taLogins);
        //fill TAs to limit
        for (String taLogin : taLogins) {
            for (int i = 0; i < numStudsNeeded.get(taLogin); i++) {
                distribution.get(taLogin).add(handinLogins.removeFirst());
            }
        }

        //distribute remaining students (< # TAs of them) to random TAs
        //There will be < # TAs of them because we floored when we took the average so only at most n-1 could be left.
        Collections.shuffle(taLogins);
        for (String taLogin : taLogins) {
            if (!handinLogins.isEmpty()) {
                distribution.get(taLogin).add(handinLogins.removeFirst());
            } else {
                break;
            }
        }
        return true;
    }

    private void setupGradingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupGradingButtonActionPerformed
        String asgn = assignmentNameComboBox.getSelectedItem().toString();
        Assignment asgnObject = (Assignment) assignmentNameComboBox.getSelectedItem();

        //create rubric directory if it does not exist
        String directoryPath = Allocator.getCourseInfo().getRubricDir() + asgn + "/";
        Allocator.getGeneralUtilities().makeDirectory(directoryPath);

        ImageIcon icon = new javax.swing.ImageIcon("/gradesystem/resources/icons/32x32/accessories-text-editor.png"); // NOI18N
        String input = (String) JOptionPane.showInputDialog(new JFrame(), "Enter minutes of leniency:", "Set Grace Period", JOptionPane.PLAIN_MESSAGE, icon, null, "");
        int minsLeniency = Allocator.getCourseInfo().getMinutesOfLeniency();
        if ((input != null) && (input.length() != 0)) {
            minsLeniency = Integer.parseInt(input);
        }

        Map<String, Collection<String>> distribution = Allocator.getDatabaseIO().getDistribution(asgnObject.getHandinPart());
        Allocator.getRubricManager().distributeRubrics(asgnObject.getHandinPart(), distribution, minsLeniency);
}//GEN-LAST:event_setupGradingButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //new ReassignView((String) assignmentNameComboBox.getSelectedItem());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AssignmentdistView(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assignmentNameComboBox;
    private javax.swing.JButton generateDistButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMcenu2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainMenuBar;
    private backend.assignmentdist.AssignmentdistTable mainTable;
    private javax.swing.JButton setupGradingButton;
    // End of variables declaration//GEN-END:variables
}
