/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorPane.java
 *
 * Created on Sep 27, 2009, 3:05:14 AM
 */

package utils;

import javax.swing.JEditorPane;
import jsyntaxpane.DefaultSyntaxKit;

/**
 *
 * @author psastras
 */
public class EditorPane extends javax.swing.JPanel {

    /** Creates new form EditorPane */
    public EditorPane() {
        initComponents();
        DefaultSyntaxKit.initKit();
        final JEditorPane codeEditor = new JEditorPane();
        jScrollPane1.setViewportView(codeEditor);
        codeEditor.setContentType("text/java");
        codeEditor.setText("public static void main(String[] args) {\n    System.out.println(\"Hello world.\")\n}");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
