/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChartDataPanel.java
 *
 * Created on Sep 8, 2009, 3:41:34 PM
 */
package histogrammer;

import cs015Database.DatabaseInterops;
import java.util.ArrayList;
import java.util.List;
import org.jfree.data.statistics.Statistics;
import org.tmatesoft.sqljet.core.table.ISqlJetCursor;

/**
 *
 * @author Paul
 */
public class ChartDataPanel extends javax.swing.JPanel {

    /** Creates new form ChartDataPanel */
    public ChartDataPanel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }

    public void updateChartData(String asgnName) {
        try {
            ISqlJetCursor cursor = DatabaseInterops.getAllData("grades_" + asgnName);
            List<Double> l = new ArrayList<Double>();
            while (!cursor.eof()) {
                l.add(Double.parseDouble(cursor.getString("Total")));
                cursor.next();
            }
            double[] data = new double[l.size()];
            for (int i = 0; i < data.length; i++) {
                data[i] = l.get(i);
            }
            Number[] dataAsNumber = new Number[data.length];
            for (int i = 0; i < dataAsNumber.length; i++) {
                dataAsNumber[i] = (Number) data[i];
            }
            nLabel.setText("" + data.length);
            medianLabel.setText("" + Statistics.calculateMedian(l));
            meanLabel.setText("" + Statistics.calculateMean(l));
            stdDevLabel.setText("" + Statistics.getStdDev(dataAsNumber));
            chartPanel1.loadData(asgnName, data);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartPanel1 = new histogrammer.ChartPanel();
        jLabel1 = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        meanLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        medianLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stdDevLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        chartPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chartPanel1Layout = new javax.swing.GroupLayout(chartPanel1);
        chartPanel1.setLayout(chartPanel1Layout);
        chartPanel1Layout.setHorizontalGroup(
            chartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        chartPanel1Layout.setVerticalGroup(
            chartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("<html><b>Number of Students</b></html>");

        nLabel.setForeground(new java.awt.Color(30, 30, 30));
        nLabel.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("<html><b>Mean / Average</b></html>");

        meanLabel.setForeground(new java.awt.Color(30, 30, 30));
        meanLabel.setText("jLabel4");

        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("<html><b>Median</b></html>");

        medianLabel.setForeground(new java.awt.Color(30, 30, 30));
        medianLabel.setText("jLabel6");

        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("<html><b>Standard Deviation</b></html>");

        stdDevLabel.setForeground(new java.awt.Color(30, 30, 30));
        stdDevLabel.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdDevLabel)
                    .addComponent(medianLabel)
                    .addComponent(jLabel5)
                    .addComponent(meanLabel)
                    .addComponent(jLabel3)
                    .addComponent(nLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stdDevLabel)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private histogrammer.ChartPanel chartPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel meanLabel;
    private javax.swing.JLabel medianLabel;
    private javax.swing.JLabel nLabel;
    private javax.swing.JLabel stdDevLabel;
    // End of variables declaration//GEN-END:variables
}
