/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on Sep 11, 2009, 12:49:31 AM
 */

package cs015Database;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JComponent;


/**
 *
 * @author Paul
 */
public class ImagePanel extends JComponent {

    private BufferedImage _image;

    /** Creates new form BeanForm */
    public ImagePanel() {
        initComponents();
    }

    public void setImage(BufferedImage srcImage) {
        _image = srcImage;
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics g) {
        if(_image !=null) {
            this.setPreferredSize(new Dimension(_image.getWidth(), _image.getHeight()));
            this.setSize(_image.getWidth(), _image.getHeight());
            g.drawImage(_image, 0, 0, this);
        }
    }
}
