/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AssignmentDistributorGUI.java
 *
 * Created on Sep 7, 2009, 12:53:58 PM
 */
package assignment_distributor;

import cs015Database.*;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.tmatesoft.sqljet.core.SqlJetException;
import org.tmatesoft.sqljet.core.table.ISqlJetCursor;

/**
 *
 * @author Paul
 */
public class AssignmentDistributorGUI extends javax.swing.JFrame {

    /** Creates new form AssignmentDistributorGUI */
    public AssignmentDistributorGUI() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/cs015Database/accessories-text-editor.png")));
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            String[] columnNames = DatabaseInterops.getColumnNames("assignment_dist");
            assignmentNameComboBox.removeAllItems();
            for (int i = 1; i < columnNames.length; i++) {
                assignmentNameComboBox.insertItemAt(columnNames[i], assignmentNameComboBox.getItemCount());
            }
            if (assignmentNameComboBox.getItemCount() > 0) {
                assignmentNameComboBox.setSelectedIndex(0);
                this.setTitle(assignmentNameComboBox.getSelectedItem() + " - cs015 Assignment Distributor");
            }

        } catch (SqlJetException e) {
            e.printStackTrace();
        }
        fillTable();
        this.setLocationRelativeTo(null);

    }

    private void fillTable() {

        try {
            ISqlJetCursor cursor = DatabaseInterops.getAllData("assignment_dist");
            mainTable.removeAll();
            mainTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{}));
            mainTable.removeAll();
            DefaultTableModel m = (DefaultTableModel) mainTable.getModel();

            m.addColumn("TA Login");
            m.addColumn("Number of Students to Grade");
            try {
                while (!cursor.eof()) {
                    String s = cursor.getString((String) assignmentNameComboBox.getSelectedItem());
                    String[] ss;
                    if (s == null) {
                        s = "";
                    }
                    ss = s.split(",");
                    String[] sss = {cursor.getString("taLogin"), Integer.toString(ss.length)};
                    if (s.isEmpty()) {
                        sss[1] = "0";
                    }
                    m.insertRow(mainTable.getRowCount(), sss);
                    cursor.next();
                }
            } finally {
                cursor.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new cs015Database.Table();
        assignmentNameComboBox = new javax.swing.JComboBox();
        redistributeButton = new javax.swing.JButton();
        generateDistButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        mainTable.setFocusable(false);
        jScrollPane1.setViewportView(mainTable);

        assignmentNameComboBox.setFocusable(false);
        assignmentNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentNameComboBoxActionPerformed(evt);
            }
        });

        redistributeButton.setText("1. Redistribute");
        redistributeButton.setFocusable(false);
        redistributeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redistributeButtonActionPerformed(evt);
            }
        });

        generateDistButton.setText("2. Generate Grading Assignments");
        generateDistButton.setFocusable(false);
        generateDistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDistButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        mainMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenuBar.add(jMenu2);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(assignmentNameComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(redistributeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateDistButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assignmentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateDistButton)
                    .addComponent(redistributeButton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignmentNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentNameComboBoxActionPerformed
        this.setTitle(assignmentNameComboBox.getSelectedItem() + " - cs015 Assignment Distributor");
        fillTable();
    }//GEN-LAST:event_assignmentNameComboBoxActionPerformed

    private void redistributeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redistributeButtonActionPerformed
        int[] numToGrade = new int[mainTable.getModel().getRowCount()];
        TableModel m = mainTable.getModel();

        int index = (int) (Math.random() * numToGrade.length);
        for (int i = 0; i < DatabaseInterops.STUD_LOGINS.length; i++, index++) {
            numToGrade[index % numToGrade.length]++;
        }
        for (int i = 0; i < numToGrade.length; i++) {
            m.setValueAt(numToGrade[i], i, 1);
        }
    }//GEN-LAST:event_redistributeButtonActionPerformed

    private void generateDistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDistButtonActionPerformed
        String[] studNames = DatabaseInterops.getStudentNames();
        String[] taNames = DatabaseInterops.getTANames();
        String[] studentsToGrade = new String[taNames.length];
        Arrays.fill(studentsToGrade, "");
        String[] tasWithBlacklist = DatabaseInterops.getColumnData("taLogin", "blacklist");
        ArrayDeque<String> ad = new ArrayDeque<String>();
        for (String s : studNames) {
            ad.add(s);
        }
        int index = (int) (Math.random() * taNames.length);
        Arrays.sort(tasWithBlacklist);
        while (!ad.isEmpty()) {
            if (Arrays.binarySearch(tasWithBlacklist, ad.peekLast()) >= 0) {
                String blacklistedStuds = getBlacklist(ad.peekLast());
                if (blacklistedStuds.contains(ad.peekLast())) {
                    ad.addFirst(ad.pollLast());
                }
            } else {
                if (studentsToGrade[index % studentsToGrade.length].isEmpty()) {
                    studentsToGrade[index++ % studentsToGrade.length] += ad.pollLast();
                } else {
                    studentsToGrade[index++ % studentsToGrade.length] +=  ", " + ad.pollLast();
                }
            }
        }
        try {
            String[] colNames = DatabaseInterops.getColumnNames("assignment_dist");
            int colIndex = 0;
            for (int i = 0; i < colNames.length; i++, colIndex++) {
                if (colNames[i].compareToIgnoreCase((String) assignmentNameComboBox.getSelectedItem()) == 0) {
                    break;
                }
            }
            for (int i = 0; i < tasWithBlacklist.length; i++) {
                long rowid = DatabaseInterops.getRowID("assignment_dist", "taLoginDist", taNames[i]);
                Object[] o = DatabaseInterops.getDataRow("assignment_dist", rowid);
                o[colIndex] = studentsToGrade[i];
                DatabaseInterops.update(rowid, "assignment_dist", o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateDistButtonActionPerformed

    private String getBlacklist(String taName) {
        try {
            ISqlJetCursor cursor = DatabaseInterops.getData("blacklist", "ta_blist_logins", taName);
            return cursor.getString("studLogins");
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AssignmentDistributorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assignmentNameComboBox;
    private javax.swing.JButton generateDistButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainMenuBar;
    private cs015Database.Table mainTable;
    private javax.swing.JButton redistributeButton;
    // End of variables declaration//GEN-END:variables
}
