/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Dec 26, 2009, 6:29:58 PM
 */

package backend;

import backend.assignmentdist.AssignmentdistView;
import backend.gradereport.GradeReportView;
import backend.histogram.HistogramView;
import frontend.FileViewerView;
import java.awt.CardLayout;
import java.io.File;
import utils.Allocator;

/**
 *
 * @author jeldridg
 */
public class NewBackend extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewBackend() {
        initComponents();

        //populate assignment list
        assignmentList.setListData(DatabaseIO.getProjectNames());

        //populate student list
        studentList.setListData(DatabaseIO.getStudentNames());

        

        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, singleSelectedPanel.getName());
        singleSelectedPanel.setVisible(true);
        
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList();
        studentFilter = new javax.swing.JTextField();
        assignmentsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignmentList = new javax.swing.JList();
        studentsLabel = new javax.swing.JLabel();
        asgnSelectAllButton = new javax.swing.JButton();
        studentSelectAllButton = new javax.swing.JButton();
        asgnTypeComboBox = new javax.swing.JComboBox();
        asgnSelectLabel = new javax.swing.JLabel();
        asgnSelectNoneButton = new javax.swing.JButton();
        studentSelectNoneButton = new javax.swing.JButton();
        studentSelectLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        singleSelectedPanel = new javax.swing.JPanel();
        multiSelectedPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        centerPanel = new javax.swing.JPanel();
        selectedAsgnLabel = new javax.swing.JLabel();
        generateDistButton = new javax.swing.JButton();
        previewRubricButton = new javax.swing.JButton();
        reassignGradingButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        viewGradingStandardsButton = new javax.swing.JButton();
        sendGradesButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        importGradesButton = new javax.swing.JButton();
        runCodeButton = new javax.swing.JButton();
        testCodeButton = new javax.swing.JButton();
        viewRubricButton = new javax.swing.JButton();
        extensionButton = new javax.swing.JButton();
        exemptionButton = new javax.swing.JButton();
        demoButton = new javax.swing.JButton();
        printCodeButton = new javax.swing.JButton();
        printRubricButton = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        blacklistButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        exportDBButton = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gradesystem.GradeSystemApp.class).getContext().getResourceMap(NewBackend.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        leftPanel.setMinimumSize(new java.awt.Dimension(350, 0));
        leftPanel.setName("leftPanel"); // NOI18N
        leftPanel.setPreferredSize(new java.awt.Dimension(350, 522));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        studentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        studentList.setMaximumSize(new java.awt.Dimension(160, 95));
        studentList.setMinimumSize(new java.awt.Dimension(140, 95));
        studentList.setName("studentList"); // NOI18N
        studentList.setPreferredSize(new java.awt.Dimension(150, 95));
        jScrollPane2.setViewportView(studentList);

        studentFilter.setText(resourceMap.getString("studentFilter.text")); // NOI18N
        studentFilter.setName("studentFilter"); // NOI18N

        assignmentsLabel.setText(resourceMap.getString("assignmentsLabel.text")); // NOI18N
        assignmentsLabel.setName("assignmentsLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        assignmentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        assignmentList.setName("assignmentList"); // NOI18N
        assignmentList.setPreferredSize(new java.awt.Dimension(140, 95));
        jScrollPane1.setViewportView(assignmentList);

        studentsLabel.setText(resourceMap.getString("studentsLabel.text")); // NOI18N
        studentsLabel.setName("studentsLabel"); // NOI18N

        asgnSelectAllButton.setText(resourceMap.getString("asgnSelectAllButton.text")); // NOI18N
        asgnSelectAllButton.setName("asgnSelectAllButton"); // NOI18N
        asgnSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asgnSelectAllButtonActionPerformed(evt);
            }
        });

        studentSelectAllButton.setText(resourceMap.getString("studentSelectAllButton.text")); // NOI18N
        studentSelectAllButton.setName("studentSelectAllButton"); // NOI18N
        studentSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSelectAllButtonActionPerformed(evt);
            }
        });

        asgnTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Item 2", "Item 3", "Item 4" }));
        asgnTypeComboBox.setName("asgnTypeComboBox"); // NOI18N

        asgnSelectLabel.setText(resourceMap.getString("asgnSelectLabel.text")); // NOI18N
        asgnSelectLabel.setName("asgnSelectLabel"); // NOI18N

        asgnSelectNoneButton.setText(resourceMap.getString("asgnSelectNoneButton.text")); // NOI18N
        asgnSelectNoneButton.setName("asgnSelectNoneButton"); // NOI18N
        asgnSelectNoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asgnSelectNoneButtonActionPerformed(evt);
            }
        });

        studentSelectNoneButton.setText(resourceMap.getString("studentSelectNoneButton.text")); // NOI18N
        studentSelectNoneButton.setName("studentSelectNoneButton"); // NOI18N
        studentSelectNoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSelectNoneButtonActionPerformed(evt);
            }
        });

        studentSelectLabel.setText(resourceMap.getString("studentSelectLabel.text")); // NOI18N
        studentSelectLabel.setName("studentSelectLabel"); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(assignmentsLabel)
                    .addComponent(asgnTypeComboBox, 0, 154, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(asgnSelectLabel)
                        .addGap(18, 18, 18)
                        .addComponent(asgnSelectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asgnSelectNoneButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(studentSelectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(studentSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentSelectNoneButton))
                    .addComponent(studentsLabel)
                    .addComponent(studentFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignmentsLabel)
                    .addComponent(studentsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentSelectNoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(asgnSelectLabel)
                        .addComponent(asgnSelectNoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asgnSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentSelectLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asgnTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftPanel);

        jPanel2.setMaximumSize(new java.awt.Dimension(750, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 0));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 561));

        cardPanel.setName("cardPanel"); // NOI18N
        cardPanel.setLayout(new CardLayout());
        cardPanel.setLayout(new java.awt.CardLayout());

        singleSelectedPanel.setName("singlePanel"); // NOI18N

        javax.swing.GroupLayout singleSelectedPanelLayout = new javax.swing.GroupLayout(singleSelectedPanel);
        singleSelectedPanel.setLayout(singleSelectedPanelLayout);
        singleSelectedPanelLayout.setHorizontalGroup(
            singleSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        singleSelectedPanelLayout.setVerticalGroup(
            singleSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        cardPanel.add(singleSelectedPanel, "single_student");

        multiSelectedPanel.setName("multiPanel"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout multiSelectedPanelLayout = new javax.swing.GroupLayout(multiSelectedPanel);
        multiSelectedPanel.setLayout(multiSelectedPanelLayout);
        multiSelectedPanelLayout.setHorizontalGroup(
            multiSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiSelectedPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        multiSelectedPanelLayout.setVerticalGroup(
            multiSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiSelectedPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        cardPanel.add(multiSelectedPanel, "multiPanel");

        jSplitPane2.setName("jSplitPane2"); // NOI18N

        centerPanel.setName("centerPanel"); // NOI18N

        selectedAsgnLabel.setText(resourceMap.getString("selectedAsgnLabel.text")); // NOI18N
        selectedAsgnLabel.setName("selectedAsgnLabel"); // NOI18N

        generateDistButton.setIcon(resourceMap.getIcon("generateDistButton.icon")); // NOI18N
        generateDistButton.setText(resourceMap.getString("generateDistButton.text")); // NOI18N
        generateDistButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        generateDistButton.setIconTextGap(5);
        generateDistButton.setName("generateDistButton"); // NOI18N
        generateDistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDistButtonActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gradesystem.GradeSystemApp.class).getContext().getActionMap(NewBackend.class, this);
        previewRubricButton.setAction(actionMap.get("previewRubricButtonActionPerformed")); // NOI18N
        previewRubricButton.setIcon(resourceMap.getIcon("previewRubricButton.icon")); // NOI18N
        previewRubricButton.setText(resourceMap.getString("previewRubricButton.text")); // NOI18N
        previewRubricButton.setToolTipText(resourceMap.getString("previewRubricButton.toolTipText")); // NOI18N
        previewRubricButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        previewRubricButton.setIconTextGap(5);
        previewRubricButton.setName("previewRubricButton"); // NOI18N
        previewRubricButton.setPreferredSize(new java.awt.Dimension(170, 29));

        reassignGradingButton.setIcon(resourceMap.getIcon("reassignGradingButton.icon")); // NOI18N
        reassignGradingButton.setText(resourceMap.getString("reassignGradingButton.text")); // NOI18N
        reassignGradingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reassignGradingButton.setIconTextGap(5);
        reassignGradingButton.setName("reassignGradingButton"); // NOI18N
        reassignGradingButton.setPreferredSize(new java.awt.Dimension(170, 29));
        reassignGradingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reassignGradingButtonActionPerformed(evt);
            }
        });

        statisticsButton.setIcon(resourceMap.getIcon("statisticsButton.icon")); // NOI18N
        statisticsButton.setText(resourceMap.getString("statisticsButton.text")); // NOI18N
        statisticsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statisticsButton.setIconTextGap(5);
        statisticsButton.setName("statisticsButton"); // NOI18N
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        viewGradingStandardsButton.setIcon(resourceMap.getIcon("viewGradingStandardsButton.icon")); // NOI18N
        viewGradingStandardsButton.setMnemonic('V');
        viewGradingStandardsButton.setText(resourceMap.getString("viewGradingStandardsButton.text")); // NOI18N
        viewGradingStandardsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewGradingStandardsButton.setIconTextGap(5);
        viewGradingStandardsButton.setMaximumSize(new java.awt.Dimension(175, 29));
        viewGradingStandardsButton.setName("viewGradingStandardsButton"); // NOI18N
        viewGradingStandardsButton.setPreferredSize(new java.awt.Dimension(170, 29));
        viewGradingStandardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGradingStandardsButtonActionPerformed(evt);
            }
        });

        sendGradesButton.setIcon(resourceMap.getIcon("sendGradesButton.icon")); // NOI18N
        sendGradesButton.setText(resourceMap.getString("sendGradesButton.text")); // NOI18N
        sendGradesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sendGradesButton.setIconTextGap(5);
        sendGradesButton.setName("sendGradesButton"); // NOI18N
        sendGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendGradesButtonActionPerformed(evt);
            }
        });

        openButton.setIcon(resourceMap.getIcon("openButton.icon")); // NOI18N
        openButton.setMnemonic('O');
        openButton.setText(resourceMap.getString("openButton.text")); // NOI18N
        openButton.setFocusable(false);
        openButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        openButton.setIconTextGap(5);
        openButton.setName("openButton"); // NOI18N
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        importGradesButton.setText(resourceMap.getString("importGradesButton.text")); // NOI18N
        importGradesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        importGradesButton.setIconTextGap(5);
        importGradesButton.setName("importGradesButton"); // NOI18N
        importGradesButton.setPreferredSize(new java.awt.Dimension(170, 29));
        importGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importGradesButtonActionPerformed(evt);
            }
        });

        runCodeButton.setIcon(resourceMap.getIcon("runCodeButton.icon")); // NOI18N
        runCodeButton.setText(resourceMap.getString("runCodeButton.text")); // NOI18N
        runCodeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        runCodeButton.setIconTextGap(5);
        runCodeButton.setName("runCodeButton"); // NOI18N

        testCodeButton.setIcon(resourceMap.getIcon("testCodeButton.icon")); // NOI18N
        testCodeButton.setText(resourceMap.getString("testCodeButton.text")); // NOI18N
        testCodeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        testCodeButton.setIconTextGap(5);
        testCodeButton.setName("testCodeButton"); // NOI18N

        viewRubricButton.setIcon(resourceMap.getIcon("viewRubricButton.icon")); // NOI18N
        viewRubricButton.setText(resourceMap.getString("viewRubricButton.text")); // NOI18N
        viewRubricButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewRubricButton.setIconTextGap(5);
        viewRubricButton.setName("viewRubricButton"); // NOI18N

        extensionButton.setIcon(resourceMap.getIcon("extensionButton.icon")); // NOI18N
        extensionButton.setText(resourceMap.getString("extensionButton.text")); // NOI18N
        extensionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        extensionButton.setIconTextGap(5);
        extensionButton.setName("extensionButton"); // NOI18N

        exemptionButton.setIcon(resourceMap.getIcon("exemptionButton.icon")); // NOI18N
        exemptionButton.setText(resourceMap.getString("exemptionButton.text")); // NOI18N
        exemptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exemptionButton.setIconTextGap(5);
        exemptionButton.setName("exemptionButton"); // NOI18N

        demoButton.setIcon(resourceMap.getIcon("demoButton.icon")); // NOI18N
        demoButton.setText(resourceMap.getString("demoButton.text")); // NOI18N
        demoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        demoButton.setIconTextGap(5);
        demoButton.setName("demoButton"); // NOI18N

        printCodeButton.setIcon(resourceMap.getIcon("printCodeButton.icon")); // NOI18N
        printCodeButton.setText(resourceMap.getString("printCodeButton.text")); // NOI18N
        printCodeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        printCodeButton.setIconTextGap(5);
        printCodeButton.setName("printCodeButton"); // NOI18N

        printRubricButton.setIcon(resourceMap.getIcon("printRubricButton.icon")); // NOI18N
        printRubricButton.setText(resourceMap.getString("printRubricButton.text")); // NOI18N
        printRubricButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        printRubricButton.setIconTextGap(5);
        printRubricButton.setName("printRubricButton"); // NOI18N

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectedAsgnLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(printCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printRubricButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(viewRubricButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(generateDistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(previewRubricButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewGradingStandardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reassignGradingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4))
                        .addGroup(centerPanelLayout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(demoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(testCodeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(runCodeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exemptionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extensionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendGradesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statisticsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(importGradesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedAsgnLabel)
                .addGap(379, 379, 379)
                .addComponent(printCodeButton)
                .addGap(18, 18, 18)
                .addComponent(viewRubricButton)
                .addGap(4, 4, 4)
                .addComponent(printRubricButton)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generateDistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(importGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reassignGradingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(previewRubricButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewGradingStandardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(demoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(8, 8, 8)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(statisticsButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(sendGradesButton)
                    .addGap(18, 18, 18)
                    .addComponent(extensionButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(exemptionButton)
                    .addGap(18, 18, 18)
                    .addComponent(openButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(runCodeButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(testCodeButton)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        jSplitPane2.setLeftComponent(centerPanel);

        rightPanel.setName("rightPanel"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        blacklistButton.setIcon(resourceMap.getIcon("blacklistButton.icon")); // NOI18N
        blacklistButton.setText(resourceMap.getString("blacklistButton.text")); // NOI18N
        blacklistButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blacklistButton.setIconTextGap(5);
        blacklistButton.setName("blacklistButton"); // NOI18N

        configButton.setIcon(resourceMap.getIcon("configButton.icon")); // NOI18N
        configButton.setText(resourceMap.getString("configButton.text")); // NOI18N
        configButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configButton.setIconTextGap(5);
        configButton.setName("configButton"); // NOI18N

        exportDBButton.setIcon(resourceMap.getIcon("exportDBButton.icon")); // NOI18N
        exportDBButton.setText(resourceMap.getString("exportDBButton.text")); // NOI18N
        exportDBButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exportDBButton.setIconTextGap(5);
        exportDBButton.setName("exportDBButton"); // NOI18N

        jButton11.setIcon(resourceMap.getIcon("jButton11.icon")); // NOI18N
        jButton11.setText(resourceMap.getString("jButton11.text")); // NOI18N
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.setIconTextGap(5);
        jButton11.setName("jButton11"); // NOI18N

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportDBButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(configButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blacklistButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(blacklistButton)
                .addGap(18, 18, 18)
                .addComponent(configButton)
                .addGap(18, 18, 18)
                .addComponent(exportDBButton)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(rightPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateDistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDistButtonActionPerformed
        AssignmentdistView av = new AssignmentdistView();
        av.setLocationRelativeTo(null);
        av.setVisible(true);
}//GEN-LAST:event_generateDistButtonActionPerformed

    private void reassignGradingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reassignGradingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reassignGradingButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        HistogramView hv = new HistogramView();
        hv.setLocationRelativeTo(null);
        hv.setVisible(true);
}//GEN-LAST:event_statisticsButtonActionPerformed

    private void viewGradingStandardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGradingStandardsButtonActionPerformed
        FileViewerView  fvv = new FileViewerView();
        String project = (String) assignmentList.getSelectedValue();

        fvv.openFile(new File(Allocator.getConstants().getAssignmentDir() + project + "/" + Allocator.getConstants().getDeductionsListFilename()));
        fvv.setLocationRelativeTo(null);
        fvv.setVisible(true);
}//GEN-LAST:event_viewGradingStandardsButtonActionPerformed

    private void sendGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGradesButtonActionPerformed
        GradeReportView grv = new GradeReportView();
        grv.setLocationRelativeTo(null);
        grv.setVisible(true);
}//GEN-LAST:event_sendGradesButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        Allocator.getFrontendUtilities().openStudentProject(this.getSelectedAssignment(), this.getSelectedStudent());
}//GEN-LAST:event_openButtonActionPerformed

    private void importGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importGradesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importGradesButtonActionPerformed

    private void asgnSelectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asgnSelectAllButtonActionPerformed
        assignmentList.setSelectionInterval(0, assignmentList.getModel().getSize() - 1);
    }//GEN-LAST:event_asgnSelectAllButtonActionPerformed

    private void studentSelectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSelectAllButtonActionPerformed
        studentList.setSelectionInterval(0, studentList.getModel().getSize() - 1);
    }//GEN-LAST:event_studentSelectAllButtonActionPerformed

    private void studentSelectNoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSelectNoneButtonActionPerformed
        studentList.clearSelection();
    }//GEN-LAST:event_studentSelectNoneButtonActionPerformed

    private void asgnSelectNoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asgnSelectNoneButtonActionPerformed
        assignmentList.clearSelection();
    }//GEN-LAST:event_asgnSelectNoneButtonActionPerformed

   /**
     * Returns the currently selected assignment as a String.
     *
     * @return
     */
    private String[] getSelectedAssignments(){
        return (String[]) assignmentList.getSelectedValues();
    }

    private String getSelectedAssignment(){
        return (String) assignmentList.getSelectedValue();
    }

    /**
     * Returns the currently selected student as a String.
     *
     * @return
     */
    private String getSelectedStudent(){
        return (String) studentList.getSelectedValue();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBackend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asgnSelectAllButton;
    private javax.swing.JLabel asgnSelectLabel;
    private javax.swing.JButton asgnSelectNoneButton;
    private javax.swing.JComboBox asgnTypeComboBox;
    private javax.swing.JList assignmentList;
    private javax.swing.JLabel assignmentsLabel;
    private javax.swing.JButton blacklistButton;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton configButton;
    private javax.swing.JButton demoButton;
    private javax.swing.JButton exemptionButton;
    private javax.swing.JButton exportDBButton;
    private javax.swing.JButton extensionButton;
    private javax.swing.JButton generateDistButton;
    private javax.swing.JButton importGradesButton;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel multiSelectedPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JButton previewRubricButton;
    private javax.swing.JButton printCodeButton;
    private javax.swing.JButton printRubricButton;
    private javax.swing.JButton reassignGradingButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton runCodeButton;
    private javax.swing.JLabel selectedAsgnLabel;
    private javax.swing.JButton sendGradesButton;
    private javax.swing.JPanel singleSelectedPanel;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JTextField studentFilter;
    private javax.swing.JList studentList;
    private javax.swing.JButton studentSelectAllButton;
    private javax.swing.JLabel studentSelectLabel;
    private javax.swing.JButton studentSelectNoneButton;
    private javax.swing.JLabel studentsLabel;
    private javax.swing.JButton testCodeButton;
    private javax.swing.JButton viewGradingStandardsButton;
    private javax.swing.JButton viewRubricButton;
    // End of variables declaration//GEN-END:variables

}
