DROP TABLE IF EXISTS "asgn";
CREATE TABLE "asgn" ("aid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" VARCHAR NOT NULL );
INSERT INTO "asgn" VALUES(1,'TASafeHouse');
DROP TABLE IF EXISTS "blacklist";
CREATE TABLE "blacklist" ("bid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "tid" INTEGER NOT NULL , "sid" INTEGER NOT NULL );
INSERT INTO "blacklist" VALUES(1,1,1);
INSERT INTO "blacklist" VALUES(2,2,1);
DROP TABLE IF EXISTS "distribution";
CREATE TABLE "distribution" ("did" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "sid" INTEGER NOT NULL , "aid" INTEGER NOT NULL , "tid" INTEGER NOT NULL );
INSERT INTO "distribution" VALUES(1,1,2,1);
INSERT INTO "distribution" VALUES(2,2,2,1);
INSERT INTO "distribution" VALUES(3,3,2,2);
DROP TABLE IF EXISTS "exemption";
CREATE TABLE "exemption" ("xid" INTEGER PRIMARY KEY  NOT NULL , "sid" INTEGER NOT NULL , "aid" INTEGER NOT NULL , "note" TEXT);
DROP TABLE IF EXISTS "extension";
CREATE TABLE "extension" ("eid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "sid" INTEGER NOT NULL , "aid" INTEGER NOT NULL , "ontime" DATETIME NOT NULL , "note" TEXT);
DROP TABLE IF EXISTS "grade";
CREATE TABLE "grade" ("gid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "sid" INTEGER NOT NULL , "aid" INTEGER NOT NULL , "score" DOUBLE NOT NULL , "status" VARCHAR NOT NULL );
DROP TABLE IF EXISTS "student";
CREATE TABLE "student" ("sid" INTEGER PRIMARY KEY  NOT NULL ,"login" VARCHAR NOT NULL ,"firstname" VARCHAR NOT NULL ,"lastname" VARCHAR NOT NULL ,"enabled" INTEGER NOT NULL  DEFAULT 1 );
INSERT INTO "student" VALUES(1,'drs','The','Doctors',1);
INSERT INTO "student" VALUES(2,'dmorrill','Drew','Morrill',1);
INSERT INTO "student" VALUES(3,'nvarone','Nick','Varone',1);
DROP TABLE IF EXISTS "ta";
CREATE TABLE "ta" ("tid" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "login" VARCHAR NOT NULL);
INSERT INTO "ta" VALUES(1,'aunger');
INSERT INTO "ta" VALUES(2,'spoletto');
INSERT INTO "ta" VALUES(3,'jeldridg');
CREATE INDEX asgn_name ON asgn (name);
CREATE INDEX blacklist_student ON blacklist (sid);
CREATE INDEX blacklist_ta ON blacklist (tid);
CREATE INDEX distribution_asgn ON grade (aid);
CREATE INDEX distribution_ta ON distribution (tid);
CREATE INDEX exemption_asgn ON exemption (aid);
CREATE INDEX exemption_student ON exemption (sid);
CREATE INDEX extension_asgn ON extension (aid);
CREATE INDEX extension_student ON extension (sid);
CREATE INDEX grade_asgn ON grade (aid);
CREATE INDEX grade_student ON grade (sid);
CREATE INDEX ta_login ON ta (login);
