package backend.stathist;

import config.Assignment;
import config.Part;
import java.awt.CardLayout;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import utils.Allocator;

/**
 *
 * @author psastras
 * @author jeldridg
 */
public class StatHistView extends javax.swing.JFrame {

    private Map<Assignment,AssignmentChartPanel> _asgnChartMap;
    private Map<Part,AssignmentChartPanel> _partChartMap;
    private Map<String,StudentChartPanel> _studChartMap;
    private Collection<Assignment> _assignments;
    private Collection<Part> _parts;
    private Collection<String> _students;

    /** Creates new form HistogramView */
    public StatHistView(Collection<Assignment> assignments, Collection<String> students) {
        _assignments = assignments;
        _students = students;
        _asgnChartMap = new HashMap<Assignment,AssignmentChartPanel>();
        _partChartMap = new HashMap<Part,AssignmentChartPanel>();
        _studChartMap = new HashMap<String,StudentChartPanel>();
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("/gradesystem/resources/icons/32x32/x-office-drawing.png")));
        } catch (Exception e) {}
        
        initComponents();
        domoreinit();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void domoreinit() {
        
        _parts = new Vector<Part>();
        
        //create AssignmentChartPanels for each Assignment and Part
        for (Assignment a : _assignments) {
            _asgnChartMap.put(a, new AssignmentChartPanel());
            
            for (Part p : a.getParts()) {
                _partChartMap.put(p, new AssignmentChartPanel());
                _parts.add(p);
            }
        }
        
        //create StudentChartPanels for each student
        for (String s : _students) {
            _studChartMap.put(s, new StudentChartPanel());
        }
        
        
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(jPanel2Layout);
        ParallelGroup pg = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        
        for (AssignmentChartPanel acp : _asgnChartMap.values()) {
            pg.addComponent(acp, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE);
        }
        
        for (AssignmentChartPanel acp : _partChartMap.values()) {
            pg.addComponent(acp, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE);
        }
        
        for (StudentChartPanel scp : _studChartMap.values()) {
            pg.addComponent(scp, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE);
        }

        jPanel2Layout.setHorizontalGroup(pg);
        SequentialGroup sg = jPanel2Layout.createSequentialGroup();
        
        for (AssignmentChartPanel c : _asgnChartMap.values()) {
            sg.addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            sg.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        
        for (AssignmentChartPanel c : _partChartMap.values()) {
            sg.addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            sg.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        
        for (StudentChartPanel scp : _studChartMap.values()) {
            sg.addComponent(scp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            sg.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        
        
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(sg));

        selectViewBox.setSelectedIndex(0);
        assignmentsRb.setSelected(true);
        allStudentsRb.setSelected(true);
        
        this.updateCharts();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asgnButtonGroup = new javax.swing.ButtonGroup();
        studButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chartPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        selectViewBox = new javax.swing.JComboBox();
        cardPanel = new javax.swing.JPanel();
        asgnControlPanel = new javax.swing.JPanel();
        assignmentsRb = new javax.swing.JRadioButton();
        partsRb = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        allStudentsRb = new javax.swing.JRadioButton();
        studentsSelectedRb = new javax.swing.JRadioButton();
        studentControlPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gradesystem.GradeSystemApp.class).getContext().getResourceMap(StatHistView.class);
        chartPanel.setBackground(resourceMap.getColor("chartPanel.background")); // NOI18N
        chartPanel.setName("chartPanel"); // NOI18N

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1654, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(chartPanel);

        optionsPanel.setName("optionsPanel"); // NOI18N

        selectViewBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By Assignment", "By Student" }));
        selectViewBox.setName("selectViewBox"); // NOI18N
        selectViewBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectViewBoxActionPerformed(evt);
            }
        });

        cardPanel.setName("cardPanel"); // NOI18N
        cardPanel.setLayout(new java.awt.CardLayout());

        asgnControlPanel.setName("asgnControlPanel"); // NOI18N

        asgnButtonGroup.add(assignmentsRb);
        assignmentsRb.setText(resourceMap.getString("assignmentsRb.text")); // NOI18N
        assignmentsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                updateCharts();
            }
        });

        asgnButtonGroup.add(partsRb);
        partsRb.setText(resourceMap.getString("partsRb.text")); // NOI18N
        partsRb.setName("partsRb"); // NOI18N
        partsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                updateCharts();
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        studButtonGroup.add(allStudentsRb);
        allStudentsRb.setText(resourceMap.getString("allStudentsRb.text")); // NOI18N
        allStudentsRb.setName("allStudentsRb"); // NOI18N
        allStudentsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                updateCharts();
            }
        });

        studButtonGroup.add(studentsSelectedRb);
        studentsSelectedRb.setText(resourceMap.getString("studentsSelectedRb.text")); // NOI18N
        studentsSelectedRb.setName("studentsSelectedRb"); // NOI18N
        studentsSelectedRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                updateCharts();
            }
        });

        javax.swing.GroupLayout asgnControlPanelLayout = new javax.swing.GroupLayout(asgnControlPanel);
        asgnControlPanel.setLayout(asgnControlPanelLayout);
        asgnControlPanelLayout.setHorizontalGroup(
            asgnControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asgnControlPanelLayout.createSequentialGroup()
                .addGroup(asgnControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asgnControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(asgnControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(assignmentsRb)
                            .addComponent(partsRb)))
                    .addGroup(asgnControlPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(asgnControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(allStudentsRb))
                    .addGroup(asgnControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentsSelectedRb)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        asgnControlPanelLayout.setVerticalGroup(
            asgnControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asgnControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignmentsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudentsRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentsSelectedRb)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        cardPanel.add(asgnControlPanel, "assignment");

        studentControlPanel.setName("studentControlPanel"); // NOI18N

        javax.swing.GroupLayout studentControlPanelLayout = new javax.swing.GroupLayout(studentControlPanel);
        studentControlPanel.setLayout(studentControlPanelLayout);
        studentControlPanelLayout.setHorizontalGroup(
            studentControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        studentControlPanelLayout.setVerticalGroup(
            studentControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        cardPanel.add(studentControlPanel, "student");

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(selectViewBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(selectViewBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void selectViewBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectViewBoxActionPerformed
    this.updateCharts();
}//GEN-LAST:event_selectViewBoxActionPerformed


    private void updateCharts() {
        CardLayout cl = (CardLayout) cardPanel.getLayout();

        //see assignment histograms
        if (selectViewBox.getSelectedItem().equals("By Assignment")) {
            cl.show(cardPanel, "assignment");
            for (String s : _students) {
                _studChartMap.get(s).setVisible(false);
            }
            if (assignmentsRb.isSelected()) {                           //show assignments
                for (Part p : _parts) {
                    _partChartMap.get(p).setVisible(false);
                }
                for (Assignment a : _assignments) {
                    AssignmentChartPanel chart = _asgnChartMap.get(a);
                    if (studentsSelectedRb.isSelected()) {
                        chart.updateChartData(a, _students);
                    }
                    else {
                        chart.updateChartData(a, Allocator.getDatabaseIO().getEnabledStudents().keySet());
                    }
                    chart.setVisible(true);
                }
            }
            else {                                                      //show parts
                for (Assignment a : _assignments) {
                    _asgnChartMap.get(a).setVisible(false);
                }
                for (Part p : _parts) {
                    AssignmentChartPanel chart = _partChartMap.get(p);
                    if (studentsSelectedRb.isSelected()) {
                        chart.updateChartData(p, _students);
                    }
                    else {
                        chart.updateChartData(p, Allocator.getDatabaseIO().getEnabledStudents().keySet());
                    }
                    chart.setVisible(true);
                }
            }
        }

        //see student performance
        else if (selectViewBox.getSelectedItem().equals("By Student")) {
            cl.show(cardPanel, "student");
            for (Assignment a : _assignments) {
                _asgnChartMap.get(a).setVisible(false);
            }
            for (Part p : _parts) {
                _partChartMap.get(p).setVisible(false);
            }
            for (String student : _students) {
                StudentChartPanel chart = _studChartMap.get(student);
                chart.updateChart(student, _assignments.toArray(new Assignment[0]));
                chart.setVisible(true);
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StatHistView(Allocator.getCourseInfo().getHandinAssignments(), Allocator.getDatabaseIO().getEnabledStudents().keySet()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allStudentsRb;
    private javax.swing.ButtonGroup asgnButtonGroup;
    private javax.swing.JPanel asgnControlPanel;
    private javax.swing.JRadioButton assignmentsRb;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JRadioButton partsRb;
    private javax.swing.JComboBox selectViewBox;
    private javax.swing.ButtonGroup studButtonGroup;
    private javax.swing.JPanel studentControlPanel;
    private javax.swing.JRadioButton studentsSelectedRb;
    // End of variables declaration//GEN-END:variables
}
