package cakehat.views.backend;

import cakehat.services.ServicesException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import cakehat.Allocator;
import cakehat.services.UserServices.ValidityCheck;
import cakehat.views.shared.ErrorView;
import java.util.Collection;
import java.util.LinkedList;
import support.utils.posix.NativeException;

/**
 *
 * @author jeldridg
 */
public class ConfigManager extends javax.swing.JFrame {

    /** Creates new form ConfigManager */
    public ConfigManager() {
        initComponents();

        addStudentsButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (allStudentsRB.isSelected()) {
                    Collection<String> studentsNotAdded = new LinkedList<String>();
                    try {
                        for (String login : Allocator.getUserServices().getStudentLogins()) {
                            try {
                                Allocator.getUserServices().addStudent(login, ValidityCheck.BYPASS);
                            } catch (ServicesException ex) {
                                studentsNotAdded.add(login);
                            }
                        }

                        if (!studentsNotAdded.isEmpty()) {
                            new ErrorView("The following students were not added to the database: " +
                                          studentsNotAdded + ".");
                        }
                    } catch(NativeException ex) {
                        new ErrorView(ex, "Unable to add students because student logins could not be retrieved");
                    }
                }
                else {
                    String login = loginText.getText();
                    try {
                        if (firstNameText.getText().equals("") || lastNameText.getText().equals("")) {
                            Allocator.getUserServices().addStudent(login,
                                    ValidityCheck.CHECK);
                        }
                        else {
                            Allocator.getUserServices().addStudent(login,
                                    firstNameText.getText(),
                                    lastNameText.getText(),
                                    ValidityCheck.CHECK);
                        }
                    } catch (ServicesException ex) {
                        new ErrorView(ex, "Adding student " + login + " to the database failed.");
                    }
                }
            }
        } );
        
        allStudentsRB.setSelected(true);

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whichStudentsBG = new javax.swing.ButtonGroup();
        whichPartsBG = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        databasePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        allStudentsRB = new javax.swing.JRadioButton();
        oneStudentRB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        loginText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        addStudentsButton = new javax.swing.JButton();
        configPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        databasePanel.setName("databasePanel"); // NOI18N

        jLabel2.setText("<html><b>Add Students to Database:</b></html>");
        jLabel2.setName("jLabel2"); // NOI18N

        whichStudentsBG.add(allStudentsRB);
        allStudentsRB.setText("All From Group");
        allStudentsRB.setName("allStudentsRB"); // NOI18N

        whichStudentsBG.add(oneStudentRB);
        oneStudentRB.setText("Individual Student");
        oneStudentRB.setName("oneStudentRB"); // NOI18N

        jLabel3.setText("Login:");
        jLabel3.setName("jLabel3"); // NOI18N

        loginText.setName("loginText"); // NOI18N

        jLabel4.setText("<html>Name (optional; if none <br/>given, will snoop login)</html>");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("First:");
        jLabel5.setName("jLabel5"); // NOI18N

        firstNameText.setName("firstNameText"); // NOI18N

        jLabel6.setText("Last:");
        jLabel6.setName("jLabel6"); // NOI18N

        lastNameText.setName("lastNameText"); // NOI18N

        addStudentsButton.setText("Add To Database");
        addStudentsButton.setName("addStudentsButton"); // NOI18N

        javax.swing.GroupLayout databasePanelLayout = new javax.swing.GroupLayout(databasePanel);
        databasePanel.setLayout(databasePanelLayout);
        databasePanelLayout.setHorizontalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(databasePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStudentsRB)
                                    .addComponent(oneStudentRB)))
                            .addGroup(databasePanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(databasePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loginText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                    .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, databasePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(firstNameText))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, databasePanelLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(lastNameText))))))
                        .addGap(220, 220, 220))
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(addStudentsButton)))
                .addContainerGap())
        );
        databasePanelLayout.setVerticalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudentsRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneStudentRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addStudentsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Database Manager", databasePanel);

        configPanel.setName("configPanel"); // NOI18N

        jLabel1.setText("TO-DO!");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Config File Manager", configPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentsButton;
    private javax.swing.JRadioButton allStudentsRB;
    private javax.swing.JPanel configPanel;
    private javax.swing.JPanel databasePanel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextField loginText;
    private javax.swing.JRadioButton oneStudentRB;
    private javax.swing.ButtonGroup whichPartsBG;
    private javax.swing.ButtonGroup whichStudentsBG;
    // End of variables declaration//GEN-END:variables

}
